name: Build and Publish Electron App

on:
  push:
    tags:
      - "v*" # Triggers the workflow on new tags starting with 'v'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [windows-latest] # Builds for macOS, Windows, and Linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Use the appropriate Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build Electron app
        run: npm run build

      - name: Publish to GitHub Releases
        if: startsWith(matrix.os, 'ubuntu') # Only publish once, from Ubuntu
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release
